# Generated by Django 4.1.3 on 2022-11-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='uploader_name',
            field=models.CharField(max_length=30),
        ),
    ]
