# Generated by Django 4.1.2 on 2022-10-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employe',
            new_name='Animal',
        ),
    ]
