# Generated by Django 4.1.3 on 2022-11-29 08:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_rename_person_persons'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
